### ISSUE TITLE
Is there a discrete auto encoder with a LSTM predictor implement in your code?

### ISSUE THREAD

**Issue by gouxiangchen** [dhruvramani/model-based-atari#1]
Thanks for sharing your helpful code

In the original paper I've noticed that there is another stream which takes current frames and target frame as input and output a discrete latent code with a bit LSTM predictor.

But in your code the target frame seems only used to calculate the loss.. I can not find the implementation about the discrete code..

I‘m sorry if any misunderstanding 😅

**Comment by dhruvramani** [comment]
Hi!
The discrete latent code with a bit LSTM predictor hasn't been implemented here. The one implemented is the most basic deterministic model in the original code. Do check it out and feel free to contribute. The link to the code is mentioned at the end of README.

**Comment by gouxiangchen** [comment]
Thanks for your reply !
I will read the original code for more details. And I wonder if the basic model could perform well  without a bit predictor to predict the next frame and the reward? Did you test it? 
Anyway, thanks again, your code is helpful!
